export const INJECTION_TOKENS = {
	API_GATEWAY_CONFIG: Symbol("API_GATEWAY_CONFIG"),
	AUTH_SERVICE_CONFIG: Symbol("AUTH_SERVICE_CONFIG"),
	NOTIFICATION_SERVICE_CONFIG: Symbol("NOTIFICATION_SERVICE_CONFIG"),
	KAFKA_SERVICE: Symbol("KAFKA_SERVICE"),
	BULLMQ_EMAIL_QUEUE: "BULLMQ_EMAIL_QUEUE", // This is a string as BullMQ requires string queue names
};
